#!/usr/bin/env bash
# poll-and-dispatch.sh — one tick of the harness outer loop.
#
# Deterministic bash. NO LLM in the decision path. The if/elif chain in the
# advance loop IS the state machine; the artifacts on disk ARE the state.
# Every section maps to an invariant in designInvariants.md — when this script
# and the prose disagree, that doc is the tiebreaker.
#
# Generated by /harness-init. Safe to edit — see the dispatcher-explained.md
# reference for what each section does and what is safe to change.

# Serialize against concurrent ticks on this node (cron + /loop, etc.). (Inv 5)
exec {lockfd}<"$0"; flock -n $lockfd || exit 0

set -euo pipefail

SLUG="$(git config user.email | cut -d@ -f1)"
WATCH="${WATCH_PATTERN:-prd/${SLUG}/*}"
WORKTREE_BASE="../$(basename "$PWD")-harness"
MAX_WORKTREES="${MAX_WORKTREES:-1}"
IMPLEMENT_CAP="${IMPLEMENT_CAP:-3}"   # PRD-runner retries before STUCK (the plan may be wrong)
FEEDBACK_CAP="${FEEDBACK_CAP:-5}"     # reviewer feedback rounds before STUCK
mkdir -p .harness

# Load project-local config if present (MAX_WORKTREES, WATCH_PATTERN, ...).
[[ -f .harness/env ]] && source .harness/env

worktree_for() { echo "${WORKTREE_BASE}-$1"; }

# Invariant 2: a feature/<f> is harness-owned iff prds/<f>/prd.md is committed
# to it. Hand-pushed feature/quickfix without a PRD is ignored.
has_prd() {
  git cat-file -e "origin/feature/${1}:prds/${1}/prd.md" 2>/dev/null
}

# LOCAL ADDITION (not in the canonical design-doc dispatcher): make a freshly
# created worktree runnable. A bare worktree has no gitignored files
# (node_modules, .env, generated code), so signals and the PRD runner would fail
# for reasons unrelated to the feature. If the project has no bootstrap script,
# this is a no-op and the dispatcher behaves exactly as the doc specifies.
bootstrap_worktree() {
  local wt="$1"
  if [[ -x scripts/bootstrap-worktree.sh ]]; then
    ./scripts/bootstrap-worktree.sh "$wt" || \
      echo "WARN: bootstrap-worktree.sh failed for ${wt}" >&2
  fi
}

git fetch --quiet origin

# 1. Re-attach worktrees for in-flight feature/* that lost theirs.
#    In-flight work always continues regardless of MAX_WORKTREES — the cap is on
#    NEW intake, not continuation. Order is FIFO by remote branch committerdate.
in_flight=()
for feature in $(git for-each-ref --sort=committerdate \
                   --format='%(refname:lstrip=4)' \
                   refs/remotes/origin/feature/ 2>/dev/null || true); do
  has_prd "$feature" || continue
  wt="$(worktree_for "$feature")"
  if [[ ! -d "$wt" ]]; then
    git worktree add "$wt" "feature/${feature}" 2>/dev/null && bootstrap_worktree "$wt" || true
  fi
  [[ -d "$wt" ]] && in_flight+=("$feature")
done

# 2. Claim new PRDs up to remaining capacity (lazy claim). PRDs over cap stay in
#    prd/<slug>/* as the visible waiting queue. WATCH uses git refspec glob
#    syntax (* matches one path component). Per-dev default: prd/${SLUG}/*.
#    Shared pool: set WATCH_PATTERN=prd/*/*.
capacity=$(( MAX_WORKTREES - ${#in_flight[@]} ))
if (( capacity > 0 )); then
  for branch in $(git for-each-ref --sort=committerdate \
                    --format='%(refname:lstrip=3)' \
                    "refs/remotes/origin/${WATCH}" 2>/dev/null || true); do
    (( capacity > 0 )) || break
    feature="${branch##*/}"
    # Atomic rename = claim. Push failure (non-fast-forward) means another node
    # claimed first; skip silently. (Inv 2 + 7)
    if git push origin "origin/${branch}:refs/heads/feature/${feature}" \
                       ":refs/heads/${branch}" 2>/dev/null; then
      wt="$(worktree_for "$feature")"
      git worktree add "$wt" "feature/${feature}" 2>/dev/null && bootstrap_worktree "$wt" || true
      in_flight+=("$feature")
      capacity=$(( capacity - 1 ))
    fi
  done
fi

# 3. Advance each active feature by exactly ONE step. (Inv 5: one transition
#    per tick per branch.)
for feature in ${in_flight[@]+"${in_flight[@]}"}; do
  wt="$(worktree_for "$feature")"
  [[ -d "$wt" ]] || continue
  branch="feature/${feature}"

  # Invariant 3 guard: worktree HEAD must match the branch we're advancing.
  # Skip otherwise (e.g., human manually checked out a different branch).
  current=$(git -C "$wt" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
  [[ "$current" == "$branch" ]] || continue

  # Wipe: discard uncommitted state from any crashed skill. `-fd` (not `-fdx`)
  # preserves gitignored files like node_modules. (Inv 1 + 6)
  ( cd "$wt" \
    && git reset --hard HEAD --quiet \
    && git clean -fd --quiet \
    && git reset --hard "origin/$branch" --quiet )

  # State machine: walk forward by exactly one step. Sentinel files gate each
  # transition.
  if   [[ ! -f "${wt}/specs/${feature}/.planning-done" ]]; then
       claude -p "/spec-planning ${feature}"      --cwd "${wt}"

  elif [[ ! -f "${wt}/specs/${feature}/.validated" ]]; then
       claude -p "/spec-validate ${feature}"      --cwd "${wt}"

  elif ! ( cd "${wt}" && "./prds/${feature}/run-prd-test.sh" ); then
       # Bounded retry: if the PRD runner keeps failing, the *plan* may be broken,
       # not just the code, and re-invoking implement forever burns compute. Stop
       # after IMPLEMENT_CAP attempts and flag STUCK (mirrors the local-checks
       # two-strike breaker). The stuck sentinel also triggers episodic lesson
       # capture in step 6. (Inv 8)
       attempts_file=".harness/implement-attempts-${feature}"
       attempts=$(cat "${attempts_file}" 2>/dev/null || echo 0)
       if (( attempts >= IMPLEMENT_CAP )); then
         echo "STUCK: ${feature} failed the PRD runner ${IMPLEMENT_CAP}x; the plan may be wrong. Human intervention requested." >&2
         touch ".harness/stuck-${feature}"
       else
         echo $((attempts + 1)) > "${attempts_file}"
         claude -p "/implement-mainspec ${feature}" --cwd "${wt}"
       fi

  elif [[ -x "${wt}/scripts/local-checks.sh" ]] \
       && ! ( cd "${wt}" && ./scripts/local-checks.sh ); then
       # Optional gate. Two-strike retry: auto-fix, then focused LLM fix. (Inv 8)
       attempts_file=".harness/local-check-attempts-${feature}"
       attempts=$(cat "${attempts_file}" 2>/dev/null || echo 0)
       if (( attempts >= 2 )); then
         echo "STUCK: ${feature} failed local checks twice; not progressing." >&2
         touch ".harness/stuck-${feature}"
       elif (( attempts == 0 )); then
         ( cd "${wt}" && ./scripts/local-checks.sh fix || true )
         if ! ( cd "${wt}" && git diff --quiet ); then
           ( cd "${wt}" \
             && git commit -am "chore: auto-fix lint/format" --quiet \
             && git push --quiet )
         fi
         echo 1 > "${attempts_file}"
       else
         claude -p "/fix-local-checks ${feature}" --cwd "${wt}"
         echo 2 > "${attempts_file}"
       fi

  elif ! gh pr view "${branch}" >/dev/null 2>&1; then
       gh pr create --base main --head "${branch}" --fill
       rm -f ".harness/local-check-attempts-${feature}"
       rm -f ".harness/implement-attempts-${feature}"

  # PR exists. Address reviewer findings if budget remains. Counter at
  # .harness/feedback-rounds-<f> persists for the entire PR lifetime; no reset
  # on human pushes.
  elif gh pr view "${branch}" --json reviews \
         --jq '.reviews[] | select(.state=="CHANGES_REQUESTED" or .state=="COMMENTED")' \
         2>/dev/null | grep -q .; then
       rounds_file=".harness/feedback-rounds-${feature}"
       rounds=$(cat "${rounds_file}" 2>/dev/null || echo 0)
       if (( rounds >= FEEDBACK_CAP )); then
         gh pr comment "${branch}" --body \
           "STUCK: feedback round limit (${FEEDBACK_CAP}) reached. Human intervention requested."
         touch ".harness/stuck-${feature}"
       else
         echo $((rounds + 1)) > "${rounds_file}"
         claude -p "/address-feedback ${feature}" --cwd "${wt}"
       fi
  fi
done

# 4. Cleanup pass: tear down per-feature worktree + counter files for
#    closed/merged PRs. Each finished feature is torn down independently.
for feature in $(git for-each-ref --format='%(refname:lstrip=4)' \
                   refs/remotes/origin/feature/ 2>/dev/null || true); do
  state=$(gh pr view "feature/${feature}" --json state --jq .state 2>/dev/null || echo "")
  if [[ "${state}" == "MERGED" || "${state}" == "CLOSED" ]]; then
    git worktree remove "$(worktree_for "$feature")" --force 2>/dev/null || true
    rm -f ".harness/feedback-rounds-${feature}"
    rm -f ".harness/local-check-attempts-${feature}"
    rm -f ".harness/implement-attempts-${feature}"
    rm -f ".harness/stuck-${feature}"
    rm -f ".harness/lesson-captured-${feature}"
  fi
done

# 5. Post-merge memory update — Path A (procedural/semantic, GROUND TRUTH only).
#    /learn writes Expert shards + invariants + AGENTS.md pointers + candidate
#    lints, and CURATES lessons.md. Only main (committed code) is ground truth,
#    so this is the only path allowed to bless/retire memory. ls-remote makes it
#    idempotent across nodes: first to push learn/<sha> wins; others exit. (Inv 7)
LAST="$(cat .harness/last-main-sha 2>/dev/null || echo HEAD~50)"
CUR="$(git rev-parse origin/main)"
if [[ "${CUR}" != "${LAST}" ]] \
   && ! git ls-remote --exit-code origin "learn/${CUR}" >/dev/null 2>&1; then
  claude -p "/learn --since ${LAST} --sha ${CUR}"
fi
echo "${CUR}" > .harness/last-main-sha

# 6. Episodic failure capture — Path B (learn-from-struggle, merge-or-not).
#    A terminal STUCK (steps 3) drops a .harness/stuck-<f> sentinel. For each,
#    capture at most one lesson. /capture-lesson judges whether the failure is
#    generalizable and writes NOTHING for flakes / env / bad-PRD failures. Path B
#    only APPENDS to lessons.md on a rolling memory PR; Path A (/learn) is the
#    only thing that curates. Idempotent per feature via the lesson-captured
#    marker. (CLOSED-unmerged PRs are deliberately NOT a capture trigger.)
for stuck in .harness/stuck-*; do
  [[ -e "$stuck" ]] || continue                       # literal glob = no matches
  feature="${stuck##*/stuck-}"
  [[ -f ".harness/lesson-captured-${feature}" ]] && continue
  claude -p "/capture-lesson ${feature}"
  touch ".harness/lesson-captured-${feature}"
done
